TRIALS: 10
dim: 300
evalfn: BraninCurrin_EffectiveDim
max_evals: 2000
n_initial_points: 200
batch_size: 50
min_tr_size: 200
max_reference_point:
  - -18.0
  - -6.0

verbose: true
sampler: tmvn_cyl
sigma_init: 0.125
<<<<<<< HEAD
# max_centers: 30
=======
max_centers: 10
>>>>>>> origin/rerun_cts_morbo
