TRIALS: 10
dim: 60
evalfn: rover
max_evals: 2000
n_initial_points: 200
batch_size: 50
min_tr_size: 200
max_reference_point:
  - 0.0
  - -0.5

verbose: true
sampler: tmvn_cyl
sigma_init: 0.0625
max_centers: 10
